spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_dev
    username: shop_dev_user
    password: janek
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: shop_db_create.sql